"""init schema

Revision ID: 7cdfce83dff8
Revises: (base)
Create Date: 2026-09-24 20:11:39.164001

=====================================================================
S5（见 docs/工程化门禁方案.md §5）：本文件的 downgrade() **必须真正实现**。

    CI 会实跑 `upgrade → downgrade → upgrade`。空的 `pass` 会让回滚失效，
    而"回滚不了"只会在真出事时才被发现 —— 那时已经晚了。

    写迁移时先自问：这条 DDL 反过来执行是什么？
        加列   → 删列（**数据会丢**，downgrade 里要写清楚这个代价）
        建索引 → 删索引
        改类型 → 改回去（窄化可能截断，需注释风险）

    模板刻意把未填写的 downgrade 生成为 `raise NotImplementedError`，
    而不是 Alembic 默认的 `pass` —— 让"忘了写回滚"在第一次执行时就暴露。
=====================================================================
DEP-04「Alembic 纳管既有 DDL」的落地记录（2026-09-24）
    生成方式：在**全新空库**上跑
        alembic -c aids-backend/alembic.ini revision --autogenerate -m "init schema"
    随后按 alembic/versions/README.md 第 2 步做人工审查，补写了 autogenerate
    表达不了的两处（见下方带「人工补写」标记的注释）：
        - biz_sku_stock 的 CHECK 约束 chk_stock_non_negative；
        - ai_kb_document.version 的默认值（DDL 是 1，Mixin 统一给 0）。

    实测结论（本机 MySQL 8.4.11）：本迁移在空库上 upgrade 出 38 张表，
    information_schema 与 schema.sql 建出的库逐项比对 —— 索引 146/146、
    表元信息（引擎/排序规则/表注释）38/38、CHECK 1/1 全部一致；
    列定义 419 列中仅剩 24 行已知差异，全部属于下面两类**非行为性**差异：

      ① 注释措辞：PKMixin / SoftDeleteMixin / OptimisticLockMixin 是**统一**的，
         而 DDL 逐表写法不一（例如 id 列只有少数表写了注释；deleted 列
         有的写「逻辑删除」有的写「逻辑删除: 0否 1是」）。Mixin 取多数派口径。
      ② 数值默认值的 EXTRA 标记：模型用 server_default=text("0.00")，
         MySQL 记为 DEFAULT_GENERATED（表达式默认）；DDL 的字面量默认不记。
         两者对 INSERT/UPDATE 的行为一致。

    另有 1 处**结构性**差异需知悉：CHECK 约束的实际名字被 MySQL 规范化为
    ck_<表名>_<约束名>（即 ck_biz_sku_stock_chk_stock_non_negative），
    CHECK 子句本身逐字一致。

    残余差异的权威口径仍是 docs/sql/schema.sql —— 迁移只负责让**后续变更**
    可受版本控制，不改变「DDL 是唯一来源」这条约定（见 VERSIONS.md §四）。
=====================================================================
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '7cdfce83dff8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False, comment='关联 sys_user.id'),
    sa.Column('agent_no', mysql.VARCHAR(length=32), nullable=False, comment='坐席工号'),
    sa.Column('nickname', mysql.VARCHAR(length=32), nullable=False, comment='对外展示名'),
    sa.Column('max_concurrent', mysql.TINYINT(), server_default=sa.text('5'), nullable=False, comment='最大同时接待会话数'),
    sa.Column('skill_tags', mysql.VARCHAR(length=128), server_default=sa.text('NULL'), nullable=True, comment='技能标签(逗号分隔, 用于路由)'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='启用状态: 0停用 1启用(实时在线态见Redis)'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_agent')),
    sa.UniqueConstraint('agent_no', name='uk_agent_no'),
    sa.UniqueConstraint('user_id', name='uk_user_id'),
    comment='客服坐席表'
    )
    op.create_table('ai_conversation',
    sa.Column('conversation_no', mysql.VARCHAR(length=32), nullable=False, comment='会话编号'),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False, comment='游客使用匿名会话ID(负数或独立号段)'),
    sa.Column('channel', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='来源: 1商品页 2订单页 3独立对话页'),
    sa.Column('spu_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='咨询商品(商品页来源时)'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1 AI接待中 2待人工接入 3人工接待中 4已结束'),
    sa.Column('resolved', mysql.TINYINT(), server_default=sa.text('NULL'), nullable=True, comment='是否解决: 1是 0否 (结束时按 PRD §9.6 判定)'),
    sa.Column('close_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversation')),
    sa.UniqueConstraint('conversation_no', name='uk_conversation_no'),
    comment='AI会话表'
    )
    op.create_index('idx_status_update', 'ai_conversation', ['status', 'update_time'], unique=False)
    op.create_index('idx_user_id', 'ai_conversation', ['user_id', 'status'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('conversation_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('message_id', mysql.BIGINT(unsigned=True), nullable=False, comment='针对的助手消息'),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('rating', mysql.TINYINT(), nullable=False, comment='评价: 1赞 -1踩'),
    sa.Column('comment', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='补充说明'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback')),
    sa.UniqueConstraint('message_id', 'user_id', name='uk_message_user'),
    comment='AI会话评价表'
    )
    op.create_index('idx_conversation_id', 'ai_feedback', ['conversation_id'], unique=False)
    op.create_table('ai_handoff_record',
    sa.Column('conversation_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_no', mysql.VARCHAR(length=32), server_default=sa.text('NULL'), nullable=True, comment='关联订单号(争议场景)'),
    sa.Column('reason', mysql.TINYINT(), nullable=False, comment='转接原因: 1低置信度 2用户要求 3订单争议 4多次不满 5连续未解决'),
    sa.Column('queue_status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1排队中 2接入中 3已完成 4用户放弃'),
    sa.Column('agent_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='客服人员(ai_agent.id)'),
    sa.Column('agent_name', mysql.VARCHAR(length=32), server_default=sa.text('NULL'), nullable=True),
    sa.Column('accept_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True, comment='接入时间'),
    sa.Column('close_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_handoff_record')),
    comment='转人工记录表'
    )
    op.create_index('idx_agent_status', 'ai_handoff_record', ['agent_id', 'queue_status'], unique=False)
    op.create_index('idx_conversation_id', 'ai_handoff_record', ['conversation_id'], unique=False)
    op.create_index('idx_queue_status_time', 'ai_handoff_record', ['queue_status', 'create_time'], unique=False)
    op.create_table('ai_kb_chunk',
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('domain', mysql.VARCHAR(length=16), nullable=False, comment='冗余知识域, 检索路由用'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='切片原文'),
    sa.Column('token_count', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='切片token数'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1生效 0失效(文档重建后旧切片置0)'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_kb_chunk')),
    comment='AI知识库切片表'
    )
    op.create_index('idx_document_id', 'ai_kb_chunk', ['document_id'], unique=False)
    op.create_index('idx_domain_status', 'ai_kb_chunk', ['domain', 'status'], unique=False)
    op.create_table('ai_kb_document',
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False, comment='文档标题'),
    sa.Column('domain', mysql.VARCHAR(length=16), nullable=False, comment='知识域: product/policy/faq'),
    sa.Column('file_type', mysql.VARCHAR(length=16), server_default=sa.text("'md'"), nullable=False, comment='类型: pdf/docx/md/text'),
    sa.Column('file_url', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='原始文件URL(手工录入为NULL)'),
    sa.Column('content', mysql.LONGTEXT(), nullable=True, comment='纯文本内容'),
    sa.Column('chunk_count', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='切片数量'),
    sa.Column('enabled', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='是否生效: 0否 1是'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='状态: 0待处理 1处理中 2已生效 3处理失败'),
    sa.Column('error_msg', mysql.VARCHAR(length=500), server_default=sa.text('NULL'), nullable=True, comment='处理失败原因'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    # 【人工补写】schema.sql 里这张表的 version 默认值是 1（注释「内容版本(重建索引用)」），
    # 与 OptimisticLockMixin 的统一默认 0 不同；mixin 无法表达逐表差异，故在迁移里手工对齐。
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='内容版本(重建索引用)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_kb_document')),
    comment='AI知识库文档表'
    )
    op.create_index('idx_domain_enabled', 'ai_kb_document', ['domain', 'enabled'], unique=False)
    op.create_table('ai_message',
    sa.Column('conversation_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role', mysql.TINYINT(), nullable=False, comment='角色: 1用户 2助手 3系统 4工具返回'),
    sa.Column('content', mysql.LONGTEXT(), nullable=True, comment='消息内容'),
    sa.Column('intent', mysql.VARCHAR(length=16), server_default=sa.text('NULL'), nullable=True, comment='识别意图: presale/order/aftersale/chat/handoff'),
    sa.Column('confidence', mysql.DECIMAL(precision=4, scale=3), server_default=sa.text('NULL'), nullable=True, comment='意图置信度 0-1'),
    sa.Column('retrieved_chunk_ids', mysql.JSON(), nullable=True, comment='本次检索命中的切片ID数组(溯源)'),
    sa.Column('model', mysql.VARCHAR(length=64), server_default=sa.text('NULL'), nullable=True, comment='使用的Ark模型'),
    sa.Column('prompt_tokens', mysql.INTEGER(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('completion_tokens', mysql.INTEGER(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('latency_ms', mysql.INTEGER(), server_default=sa.text('NULL'), nullable=True, comment='首字延迟ms'),
    sa.Column('filtered', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='是否被敏感词拦截: 0否 1是'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_message')),
    comment='AI消息表'
    )
    op.create_index('idx_conversation_id', 'ai_message', ['conversation_id', 'create_time'], unique=False)
    op.create_table('biz_address',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False, comment='用户ID'),
    sa.Column('receiver', mysql.VARCHAR(length=32), nullable=False, comment='收货人'),
    sa.Column('phone', mysql.VARCHAR(length=128), nullable=False, comment='联系电话密文(AES-256-GCM)'),
    sa.Column('phone_hash', mysql.CHAR(length=64), nullable=False, comment='联系电话HMAC-SHA256(仅查询, 不唯一)'),
    sa.Column('province', mysql.VARCHAR(length=32), nullable=False, comment='省'),
    sa.Column('city', mysql.VARCHAR(length=32), nullable=False, comment='市'),
    sa.Column('district', mysql.VARCHAR(length=32), nullable=False, comment='区/县'),
    sa.Column('detail', mysql.VARCHAR(length=255), nullable=False, comment='详细地址'),
    sa.Column('is_default', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='默认地址: 0否 1是'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='逻辑删除: 0否 1是'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_address')),
    comment='收货地址表'
    )
    op.create_index('idx_user_id', 'biz_address', ['user_id'], unique=False)
    op.create_table('biz_brand',
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False, comment='品牌名称'),
    sa.Column('logo', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='品牌LOGO'),
    sa.Column('description', mysql.VARCHAR(length=500), server_default=sa.text('NULL'), nullable=True, comment='品牌描述'),
    sa.Column('sort', mysql.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1启用 0禁用'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_brand')),
    sa.UniqueConstraint('name', name='uk_name'),
    comment='品牌表'
    )
    op.create_table('biz_cart',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), server_default=sa.text('1'), nullable=False, comment='数量(>0)'),
    sa.Column('checked', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='是否勾选: 0否 1是'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_cart')),
    sa.UniqueConstraint('user_id', 'sku_id', name='uk_user_sku'),
    comment='购物车表'
    )
    op.create_table('biz_category',
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), server_default=sa.text('0'), nullable=False, comment='父类目ID, 0为根'),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False, comment='类目名称'),
    sa.Column('level', mysql.TINYINT(), nullable=False, comment='层级: 1/2/3'),
    sa.Column('icon', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='图标URL'),
    sa.Column('sort', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='排序, 越小越靠前'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1启用 0禁用'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_category')),
    comment='商品分类表'
    )
    op.create_index('idx_parent_id', 'biz_category', ['parent_id'], unique=False)
    op.create_table('biz_coupon_template',
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False, comment='券名称'),
    sa.Column('type', mysql.TINYINT(), nullable=False, comment='类型: 1满减 2折扣 3无门槛'),
    sa.Column('threshold_amount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='使用门槛(满X元), 0为无门槛'),
    sa.Column('discount_amount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='优惠金额(满减/无门槛)'),
    sa.Column('discount_rate', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text('NULL'), nullable=True, comment='折扣率(折扣券, 如0.90)'),
    sa.Column('max_discount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('NULL'), nullable=True, comment='最大优惠(折扣券封顶)'),
    sa.Column('total_count', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='发放总量'),
    sa.Column('remain_count', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='剩余数量(原子扣减: UPDATE ... WHERE remain_count >= 1)'),
    sa.Column('per_limit', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='每人限领张数(应用层校验已领数)'),
    sa.Column('start_time', mysql.DATETIME(), nullable=False, comment='可领取开始时间'),
    sa.Column('end_time', mysql.DATETIME(), nullable=False, comment='可领取结束时间'),
    sa.Column('valid_days', mysql.INTEGER(), server_default=sa.text('7'), nullable=False, comment='领取后有效天数'),
    sa.Column('scope_type', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='适用范围: 1全场 2指定类目 3指定商品'),
    sa.Column('scope_ids', mysql.JSON(), nullable=True, comment='指定类目/商品ID数组'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='状态: 0草稿 1发放中 2已结束 3已下架'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='逻辑删除: 0否 1是'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_coupon_template')),
    comment='优惠券模板表'
    )
    op.create_index('idx_status_time', 'biz_coupon_template', ['status', 'start_time', 'end_time'], unique=False)
    op.create_table('biz_delivery',
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_no', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('company_code', mysql.VARCHAR(length=32), nullable=False, comment='快递公司编码(如 SF/YTO)'),
    sa.Column('company_name', mysql.VARCHAR(length=64), nullable=False, comment='快递公司名称'),
    sa.Column('delivery_no', mysql.VARCHAR(length=64), nullable=False, comment='运单号'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='状态: 0待揽收 1运输中 2派送中 3已签收 4异常'),
    sa.Column('deliver_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True, comment='发货时间'),
    sa.Column('sign_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True, comment='签收时间'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_delivery')),
    sa.UniqueConstraint('delivery_no', name='uk_delivery_no'),
    comment='运单表'
    )
    op.create_index('idx_order_no', 'biz_delivery', ['order_no'], unique=False)
    op.create_table('biz_delivery_trace',
    sa.Column('delivery_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('delivery_no', mysql.VARCHAR(length=64), nullable=False, comment='冗余运单号'),
    sa.Column('trace_time', mysql.DATETIME(), nullable=False, comment='轨迹发生时间'),
    sa.Column('status_desc', mysql.VARCHAR(length=64), nullable=False, comment='轨迹描述(如"已签收")'),
    sa.Column('location', mysql.VARCHAR(length=128), server_default=sa.text('NULL'), nullable=True, comment='所在地点'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_delivery_trace')),
    sa.UniqueConstraint('delivery_no', 'trace_time', 'status_desc', name='uk_delivery_time_desc'),
    comment='物流轨迹表'
    )
    op.create_index('idx_delivery_id', 'biz_delivery_trace', ['delivery_id'], unique=False)
    op.create_table('biz_freight_template',
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False, comment='模板名称'),
    sa.Column('free_threshold', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='包邮门槛(商品实付金额), 0为不包邮'),
    sa.Column('base_freight', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='基础运费'),
    sa.Column('remote_extra', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='偏远地区附加费'),
    sa.Column('remote_regions', mysql.JSON(), nullable=True, comment='偏远地区省份数组, 如 ["新疆","西藏"]'),
    sa.Column('is_default', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='是否默认模板: 0否 1是(全局唯一)'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1启用 0禁用'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_freight_template')),
    comment='运费模板表'
    )
    op.create_table('biz_message',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('type', mysql.TINYINT(), nullable=False, comment='类型: 1订单 2售后 3系统 4营销'),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('biz_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='关联业务ID(订单/售后单)'),
    sa.Column('is_read', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='已读: 0否 1是'),
    sa.Column('read_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_message')),
    comment='站内信表'
    )
    op.create_index('idx_user_read_time', 'biz_message', ['user_id', 'is_read', 'create_time'], unique=False)
    op.create_table('biz_order',
    sa.Column('order_no', mysql.VARCHAR(length=32), nullable=False, comment='业务订单号(对外唯一)'),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False, comment='下单用户(预留分片键)'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('10'), nullable=False, comment='状态: 10待付款 20待发货 30待收货 40待评价 50已完成 60已取消 70售后中 80已关闭'),
    sa.Column('total_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='商品总额 = Σ order_item.total_amount'),
    sa.Column('discount_amount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='优惠金额 = Σ order_item.discount_amount'),
    sa.Column('freight_amount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='运费'),
    sa.Column('pay_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='实付金额 = total - discount + freight'),
    sa.Column('refund_amount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='累计已退金额(含运费), 约束 <= pay_amount'),
    sa.Column('coupon_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='使用的用户优惠券ID(biz_user_coupon.id)'),
    sa.Column('receiver', mysql.VARCHAR(length=32), nullable=False, comment='收货人快照'),
    sa.Column('receiver_phone', mysql.VARCHAR(length=128), nullable=False, comment='电话快照密文(AES-256-GCM)'),
    sa.Column('receiver_addr', mysql.VARCHAR(length=500), nullable=False, comment='完整地址快照(省市区拼接)'),
    sa.Column('pay_type', mysql.TINYINT(), server_default=sa.text('NULL'), nullable=True, comment='支付方式: 1支付宝 2微信'),
    sa.Column('pay_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('delivery_company', mysql.VARCHAR(length=64), server_default=sa.text('NULL'), nullable=True, comment='快递公司(冗余自 biz_delivery, 列表展示用)'),
    sa.Column('delivery_no', mysql.VARCHAR(length=64), server_default=sa.text('NULL'), nullable=True, comment='主运单号(冗余自 biz_delivery)'),
    sa.Column('deliver_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True, comment='发货时间'),
    sa.Column('finish_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True, comment='完成时间'),
    sa.Column('cancel_reason', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='取消原因'),
    sa.Column('cancel_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='乐观锁版本号'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_order')),
    sa.UniqueConstraint('order_no', name='uk_order_no'),
    comment='订单主表'
    )
    op.create_index('idx_create_time', 'biz_order', ['create_time'], unique=False)
    op.create_index('idx_status_create', 'biz_order', ['status', 'create_time'], unique=False)
    op.create_index('idx_user_status', 'biz_order', ['user_id', 'status'], unique=False)
    op.create_table('biz_order_item',
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_no', mysql.VARCHAR(length=32), nullable=False, comment='冗余订单号'),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False, comment='冗余, 售后查询用'),
    sa.Column('spu_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('spu_name', mysql.VARCHAR(length=128), nullable=False, comment='商品名称快照'),
    sa.Column('sku_pic', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='SKU图片快照'),
    sa.Column('sku_specs', mysql.JSON(), nullable=True, comment='规格快照'),
    sa.Column('price', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='成交单价快照'),
    sa.Column('quantity', mysql.INTEGER(), nullable=False, comment='购买数量'),
    sa.Column('total_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='小计 = price * quantity'),
    sa.Column('discount_amount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='优惠券分摊金额(按小计比例分摊, 最后一件补差)'),
    sa.Column('pay_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='实付小计 = total_amount - discount_amount'),
    sa.Column('refund_amount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='累计已退金额, 约束 <= pay_amount'),
    sa.Column('refund_status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='售后状态: 0无 1申请中 2退款中 3已退款 4已拒绝'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_order_item')),
    comment='订单明细表'
    )
    op.create_index('idx_order_id', 'biz_order_item', ['order_id'], unique=False)
    op.create_index('idx_order_no', 'biz_order_item', ['order_no'], unique=False)
    op.create_index('idx_spu_id', 'biz_order_item', ['spu_id'], unique=False)
    op.create_index('idx_user_id', 'biz_order_item', ['user_id'], unique=False)
    op.create_table('biz_order_log',
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_no', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('from_status', mysql.TINYINT(), server_default=sa.text('NULL'), nullable=True, comment='变更前状态, NULL 表示创建'),
    sa.Column('to_status', mysql.TINYINT(), nullable=False, comment='变更后状态'),
    sa.Column('event', mysql.VARCHAR(length=32), nullable=False, comment='触发事件: SUBMIT/PAY/TIMEOUT_CANCEL/DELIVER/CONFIRM/AFTER_SALE...'),
    sa.Column('operator_type', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='操作者: 1用户 2商家 3系统 4客服'),
    sa.Column('operator_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_order_log')),
    comment='订单状态流转日志表'
    )
    op.create_index('idx_order_id', 'biz_order_log', ['order_id', 'create_time'], unique=False)
    op.create_table('biz_payment',
    sa.Column('payment_no', mysql.VARCHAR(length=32), nullable=False, comment='支付单号(商户订单号 out_trade_no)'),
    sa.Column('order_no', mysql.VARCHAR(length=32), nullable=False, comment='订单号'),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('pay_type', mysql.TINYINT(), nullable=False, comment='支付方式: 1支付宝 2微信'),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='支付金额'),
    sa.Column('refunded_amount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='累计已退金额, 约束 <= amount'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='状态: 0待支付 1已发起待回调 2成功 3失败 4已关闭'),
    sa.Column('channel_trade_no', mysql.VARCHAR(length=64), server_default=sa.text('NULL'), nullable=True, comment='渠道交易号'),
    sa.Column('channel_resp', mysql.JSON(), nullable=True, comment='渠道回调原始报文(验签后)'),
    sa.Column('callback_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True, comment='成功回调时间'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_payment')),
    sa.UniqueConstraint('channel_trade_no', name='uk_channel_trade_no'),
    sa.UniqueConstraint('payment_no', name='uk_payment_no'),
    comment='支付流水表'
    )
    op.create_index('idx_order_no', 'biz_payment', ['order_no'], unique=False)
    op.create_index('idx_status_update', 'biz_payment', ['status', 'update_time'], unique=False)
    op.create_table('biz_product_review',
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('spu_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('score', mysql.TINYINT(), nullable=False, comment='评分: 1-5星'),
    sa.Column('content', mysql.VARCHAR(length=500), server_default=sa.text('NULL'), nullable=True, comment='评价内容'),
    sa.Column('images', mysql.JSON(), nullable=True, comment='评价图片URL数组'),
    sa.Column('is_anonymous', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='匿名评价: 0否 1是'),
    sa.Column('reply', mysql.VARCHAR(length=500), server_default=sa.text('NULL'), nullable=True, comment='商家回复'),
    sa.Column('reply_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1显示 0隐藏(违规)'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_product_review')),
    sa.UniqueConstraint('order_item_id', name='uk_order_item_id'),
    comment='商品评价表'
    )
    op.create_index('idx_spu_id_score', 'biz_product_review', ['spu_id', 'score'], unique=False)
    op.create_index('idx_spu_time', 'biz_product_review', ['spu_id', 'create_time'], unique=False)
    op.create_table('biz_refund',
    sa.Column('refund_no', mysql.VARCHAR(length=32), nullable=False, comment='售后单号'),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_no', mysql.VARCHAR(length=32), nullable=False, comment='冗余订单号'),
    sa.Column('order_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('type', mysql.TINYINT(), nullable=False, comment='类型: 1仅退款 2退货退款'),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='退款金额(商品分摊金额, 运费单独退)'),
    sa.Column('freight_amount', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='退还运费(PRD §6.6: 运费全额退还)'),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=False, comment='申请原因'),
    sa.Column('evidence', mysql.JSON(), nullable=True, comment='凭证图片URL数组'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='状态: 0待审核 1已拒绝 2待退货 3待收货 4退款中 5已完成 6退款失败 7已撤销'),
    sa.Column('audit_opinion', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='审核意见'),
    sa.Column('audit_user_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='审核人'),
    sa.Column('audit_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('channel_refund_no', mysql.VARCHAR(length=64), server_default=sa.text('NULL'), nullable=True, comment='渠道退款单号'),
    sa.Column('finish_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_refund')),
    sa.UniqueConstraint('refund_no', name='uk_refund_no'),
    comment='售后单表'
    )
    op.create_index('idx_order_item_id', 'biz_refund', ['order_item_id'], unique=False)
    op.create_index('idx_order_no', 'biz_refund', ['order_no'], unique=False)
    op.create_index('idx_status', 'biz_refund', ['status'], unique=False)
    op.create_index('idx_user_id', 'biz_refund', ['user_id'], unique=False)
    op.create_table('biz_sku',
    sa.Column('spu_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku_code', mysql.VARCHAR(length=64), nullable=False, comment='SKU编码(唯一)'),
    sa.Column('specs', mysql.JSON(), nullable=False, comment='销售规格, 如 [{"k":"颜色","v":"红"},{"k":"尺寸","v":"XL"}]'),
    sa.Column('price', mysql.DECIMAL(precision=12, scale=2), nullable=False, comment='售价'),
    sa.Column('original_price', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('NULL'), nullable=True, comment='划线价'),
    sa.Column('pic', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='SKU图片'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1启用 0禁用'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_sku')),
    sa.UniqueConstraint('sku_code', name='uk_sku_code'),
    comment='SKU表'
    )
    op.create_index('idx_spu_id', 'biz_sku', ['spu_id'], unique=False)
    op.create_table('biz_sku_stock',
    sa.Column('sku_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('total_stock', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='总库存'),
    sa.Column('available_stock', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='可售库存'),
    sa.Column('locked_stock', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='锁定库存(下单未支付预扣)'),
    sa.Column('sold_stock', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='已售出库存'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='乐观锁版本号'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_sku_stock')),
    sa.UniqueConstraint('sku_id', name='uk_sku_id'),
    # 【人工补写 —— 别删】autogenerate **不会**生成 CHECK 约束（SQLAlchemy 对 MySQL
    # 的 CHECK 反射/比对不可靠），必须手工补齐 —— 这正是 alembic/versions/README.md
    # 第 2 步「人工审查」点名要盯的遗漏类型。
    # 对应 DDL：CONSTRAINT `chk_stock_non_negative` CHECK (total_stock >= 0 AND ...)
    # 这是本库唯一的 CHECK，也是「库存四段恒等式」在 DB 层的兜底（MySQL 8.0.16+ 强制）。
    sa.CheckConstraint(
        'total_stock >= 0 AND available_stock >= 0 AND locked_stock >= 0 AND sold_stock >= 0',
        name='chk_stock_non_negative',
    ),
    comment='SKU库存表'
    )
    op.create_table('biz_spu',
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=False, comment='三级类目ID'),
    sa.Column('brand_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='品牌ID'),
    sa.Column('freight_template_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='运费模板ID(PRD §6.6), NULL 用默认模板'),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False, comment='商品名称'),
    sa.Column('subtitle', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='副标题'),
    sa.Column('main_pic', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='主图URL'),
    sa.Column('detail', mysql.LONGTEXT(), nullable=True, comment='商品富文本详情'),
    sa.Column('min_price', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='SKU最低价(冗余, 列表排序用)'),
    sa.Column('max_price', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False, comment='SKU最高价(冗余)'),
    sa.Column('total_stock', mysql.INTEGER(), server_default=sa.text('0'), nullable=False, comment='总库存(冗余, 各SKU total_stock 之和)'),
    sa.Column('sales', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False, comment='销量(冗余)'),
    sa.Column('view_count', mysql.BIGINT(unsigned=True), server_default=sa.text('0'), nullable=False, comment='浏览量(异步落库)'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='状态: 0草稿 1待审核 2上架 3下架'),
    sa.Column('audit_opinion', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='审核意见'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='逻辑删除: 0否 1是'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_spu')),
    comment='SPU商品表'
    )
    op.create_index('idx_brand_id', 'biz_spu', ['brand_id'], unique=False)
    op.create_index('idx_category_status', 'biz_spu', ['category_id', 'status'], unique=False)
    op.create_table('biz_spu_image',
    sa.Column('spu_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False, comment='图片URL'),
    sa.Column('sort', mysql.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_spu_image')),
    comment='SPU图集表'
    )
    op.create_index('idx_spu_id', 'biz_spu_image', ['spu_id'], unique=False)
    op.create_table('biz_stock_log',
    sa.Column('sku_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('order_no', mysql.VARCHAR(length=32), server_default=sa.text('NULL'), nullable=True, comment='关联订单号(手动调整为NULL)'),
    sa.Column('refund_no', mysql.VARCHAR(length=32), server_default=sa.text('NULL'), nullable=True, comment='关联售后单号(退货/退款回补时)'),
    sa.Column('change_type', mysql.TINYINT(), nullable=False, comment='类型: 1下单锁定 2支付扣减 3取消释放 4手动调整 5退货入库 6退款回补'),
    sa.Column('change_num', mysql.INTEGER(), nullable=False, comment='变更数量(正入负出)'),
    sa.Column('before_num', mysql.INTEGER(), nullable=False, comment='变更前可用库存'),
    sa.Column('after_num', mysql.INTEGER(), nullable=False, comment='变更后可用库存'),
    sa.Column('operator_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='操作人(手动调整时)'),
    sa.Column('remark', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True),
    sa.Column('idempotent_key', mysql.VARCHAR(length=96), server_default=sa.text('NULL'), nullable=True, comment='幂等键(PRD §6.8), 构造规则见上'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_stock_log')),
    sa.UniqueConstraint('idempotent_key', name='uk_idempotent_key'),
    comment='库存变更流水表'
    )
    op.create_index('idx_order_no', 'biz_stock_log', ['order_no'], unique=False)
    op.create_index('idx_refund_no', 'biz_stock_log', ['refund_no'], unique=False)
    op.create_index('idx_sku_id', 'biz_stock_log', ['sku_id'], unique=False)
    op.create_table('biz_user',
    sa.Column('mobile', mysql.VARCHAR(length=128), nullable=False, comment='手机号密文(AES-256-GCM, Base64)'),
    sa.Column('mobile_hash', mysql.CHAR(length=64), nullable=False, comment='手机号HMAC-SHA256(登录查询/唯一约束)'),
    sa.Column('password', mysql.CHAR(length=60), server_default=sa.text('NULL'), nullable=True, comment='密码(BCrypt), 验证码注册可为空'),
    sa.Column('nickname', mysql.VARCHAR(length=32), server_default=sa.text('NULL'), nullable=True, comment='昵称'),
    sa.Column('avatar', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='头像URL'),
    sa.Column('gender', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='性别: 0未知 1男 2女'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1正常 0禁用'),
    sa.Column('register_channel', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='注册渠道: 1手机验证码 2密码 3微信 4支付宝'),
    sa.Column('last_login_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True, comment='最后登录时间'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='逻辑删除: 0否 1是'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user')),
    sa.UniqueConstraint('mobile_hash', name='uk_mobile_hash'),
    comment='用户表'
    )
    op.create_table('biz_user_coupon',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('coupon_id', mysql.BIGINT(unsigned=True), nullable=False, comment='biz_coupon_template.id'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1未使用 2锁定中 3已使用 4已过期 5冻结中(退款)'),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='锁定/使用的订单ID'),
    sa.Column('receive_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='领取时间'),
    sa.Column('expire_time', mysql.DATETIME(), nullable=False, comment='过期时间'),
    sa.Column('use_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biz_user_coupon')),
    comment='用户优惠券表'
    )
    op.create_index('idx_coupon_id', 'biz_user_coupon', ['coupon_id'], unique=False)
    op.create_index('idx_status_expire', 'biz_user_coupon', ['status', 'expire_time'], unique=False)
    op.create_index('idx_user_status', 'biz_user_coupon', ['user_id', 'status'], unique=False)
    op.create_table('sys_audit_log',
    sa.Column('operator_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('operator_name', mysql.VARCHAR(length=32), nullable=False, comment='冗余操作人姓名'),
    sa.Column('module', mysql.VARCHAR(length=32), nullable=False, comment='模块, 如 order/product'),
    sa.Column('action', mysql.VARCHAR(length=32), nullable=False, comment='动作, 如 ship/audit/refund'),
    sa.Column('method', mysql.VARCHAR(length=8), server_default=sa.text('NULL'), nullable=True, comment='HTTP方法'),
    sa.Column('path', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True, comment='请求路径'),
    sa.Column('params', mysql.JSON(), nullable=True, comment='请求参数(脱敏后)'),
    sa.Column('result_code', mysql.INTEGER(), server_default=sa.text('NULL'), nullable=True, comment='响应code'),
    sa.Column('ip', mysql.VARCHAR(length=64), server_default=sa.text('NULL'), nullable=True, comment='操作IP'),
    sa.Column('user_agent', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True),
    sa.Column('cost_ms', mysql.INTEGER(), server_default=sa.text('NULL'), nullable=True, comment='耗时'),
    sa.Column('trace_id', mysql.VARCHAR(length=64), server_default=sa.text('NULL'), nullable=True, comment='全链路追踪ID'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_audit_log')),
    comment='操作审计日志表'
    )
    op.create_index('idx_module_action', 'sys_audit_log', ['module', 'action'], unique=False)
    op.create_index('idx_operator_time', 'sys_audit_log', ['operator_id', 'create_time'], unique=False)
    op.create_index('idx_trace_id', 'sys_audit_log', ['trace_id'], unique=False)
    op.create_table('sys_config',
    sa.Column('config_key', mysql.VARCHAR(length=128), nullable=False, comment='配置键, 如 ai.retrieval_score_threshold'),
    sa.Column('config_value', mysql.VARCHAR(length=512), nullable=False, comment='配置值(字符串, 按 value_type 解析)'),
    sa.Column('value_type', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='值类型: 0 string 1 int 2 float 3 bool 4 json'),
    sa.Column('description', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False, comment='配置说明'),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), server_default=sa.text('0'), nullable=False, comment='最后修改人 sys_user.id'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_config')),
    sa.UniqueConstraint('config_key', name='uk_config_key'),
    comment='系统动态配置表'
    )
    op.create_table('sys_dead_letter',
    sa.Column('source', mysql.VARCHAR(length=32), nullable=False, comment='来源: KAFKA/DELAY_TASK/LOCAL_MSG'),
    sa.Column('ref_key', mysql.VARCHAR(length=128), nullable=False, comment='业务唯一键(如 order_no)'),
    sa.Column('topic', mysql.VARCHAR(length=64), server_default=sa.text('NULL'), nullable=True, comment='来源topic'),
    sa.Column('payload', mysql.JSON(), nullable=True, comment='原始消息体'),
    sa.Column('error_msg', mysql.VARCHAR(length=1000), server_default=sa.text('NULL'), nullable=True),
    sa.Column('retry_count', mysql.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='状态: 0待处理 1已重放 2已忽略'),
    sa.Column('handle_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('handler_id', mysql.BIGINT(unsigned=True), server_default=sa.text('NULL'), nullable=True, comment='处理人'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_dead_letter')),
    comment='死信表'
    )
    op.create_index('idx_ref_key', 'sys_dead_letter', ['ref_key'], unique=False)
    op.create_index('idx_source_status', 'sys_dead_letter', ['source', 'status'], unique=False)
    op.create_table('sys_local_message',
    sa.Column('biz_type', mysql.VARCHAR(length=32), nullable=False, comment='业务类型: ORDER/PAYMENT/STOCK/PRODUCT...'),
    sa.Column('biz_no', mysql.VARCHAR(length=64), nullable=False, comment='业务单号(幂等键)'),
    sa.Column('topic', mysql.VARCHAR(length=64), nullable=False, comment='目标Kafka topic'),
    sa.Column('payload', mysql.JSON(), nullable=False, comment='消息体'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='状态: 0待投递 1已投递 2投递失败(超重试上限)'),
    sa.Column('retry_count', mysql.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_retry_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='下次重试时间(指数退避)'),
    sa.Column('error_msg', mysql.VARCHAR(length=500), server_default=sa.text('NULL'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_local_message')),
    sa.UniqueConstraint('biz_type', 'biz_no', 'topic', name='uk_biz_topic'),
    comment='本地消息表'
    )
    op.create_index('idx_status_retry', 'sys_local_message', ['status', 'next_retry_time'], unique=False)
    op.create_table('sys_permission',
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), server_default=sa.text('0'), nullable=False, comment='父权限, 0为根'),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False, comment='权限名称'),
    sa.Column('type', mysql.TINYINT(), nullable=False, comment='类型: 1菜单 2按钮 3接口'),
    sa.Column('perm_code', mysql.VARCHAR(length=64), nullable=False, comment='权限标识, 如 order:ship'),
    sa.Column('path', mysql.VARCHAR(length=128), server_default=sa.text('NULL'), nullable=True, comment='前端路由/后端接口路径'),
    sa.Column('sort', mysql.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1启用 0禁用'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permission')),
    sa.UniqueConstraint('perm_code', name='uk_perm_code'),
    comment='权限表'
    )
    op.create_index('idx_parent_id', 'sys_permission', ['parent_id'], unique=False)
    op.create_table('sys_role',
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False, comment='角色名称'),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=False, comment='角色编码, 如 admin/agent/ops'),
    sa.Column('data_scope', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='数据权限范围: 1仅本人 2本部门 3全量(PRD §2.2)'),
    sa.Column('remark', mysql.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1启用 0禁用'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role')),
    sa.UniqueConstraint('code', name='uk_code'),
    comment='角色表'
    )
    op.create_table('sys_role_permission',
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role_permission')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uk_role_perm'),
    comment='角色权限关联表'
    )
    op.create_index('idx_permission_id', 'sys_role_permission', ['permission_id'], unique=False)
    op.create_table('sys_user',
    sa.Column('username', mysql.VARCHAR(length=32), nullable=False, comment='登录名'),
    sa.Column('password', mysql.CHAR(length=60), nullable=False, comment='密码(BCrypt)'),
    sa.Column('real_name', mysql.VARCHAR(length=32), server_default=sa.text('NULL'), nullable=True, comment='姓名'),
    sa.Column('mobile', mysql.VARCHAR(length=128), server_default=sa.text('NULL'), nullable=True, comment='手机号密文(AES-256-GCM)'),
    sa.Column('mobile_hash', mysql.CHAR(length=64), server_default=sa.text('NULL'), nullable=True, comment='手机号HMAC-SHA256'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text('1'), nullable=False, comment='状态: 1正常 0禁用'),
    sa.Column('last_login_time', mysql.DATETIME(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted', mysql.TINYINT(), server_default=sa.text('0'), nullable=False, comment='逻辑删除: 0否 1是'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user')),
    sa.UniqueConstraint('username', name='uk_username'),
    comment='后台用户表'
    )
    op.create_index('idx_mobile_hash', 'sys_user', ['mobile_hash'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user_role')),
    sa.UniqueConstraint('user_id', 'role_id', name='uk_user_role'),
    comment='用户角色关联表'
    )
    op.create_index('idx_role_id', 'sys_user_role', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_role_id', table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index('idx_mobile_hash', table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index('idx_permission_id', table_name='sys_role_permission')
    op.drop_table('sys_role_permission')
    op.drop_table('sys_role')
    op.drop_index('idx_parent_id', table_name='sys_permission')
    op.drop_table('sys_permission')
    op.drop_index('idx_status_retry', table_name='sys_local_message')
    op.drop_table('sys_local_message')
    op.drop_index('idx_source_status', table_name='sys_dead_letter')
    op.drop_index('idx_ref_key', table_name='sys_dead_letter')
    op.drop_table('sys_dead_letter')
    op.drop_table('sys_config')
    op.drop_index('idx_trace_id', table_name='sys_audit_log')
    op.drop_index('idx_operator_time', table_name='sys_audit_log')
    op.drop_index('idx_module_action', table_name='sys_audit_log')
    op.drop_table('sys_audit_log')
    op.drop_index('idx_user_status', table_name='biz_user_coupon')
    op.drop_index('idx_status_expire', table_name='biz_user_coupon')
    op.drop_index('idx_coupon_id', table_name='biz_user_coupon')
    op.drop_table('biz_user_coupon')
    op.drop_table('biz_user')
    op.drop_index('idx_sku_id', table_name='biz_stock_log')
    op.drop_index('idx_refund_no', table_name='biz_stock_log')
    op.drop_index('idx_order_no', table_name='biz_stock_log')
    op.drop_table('biz_stock_log')
    op.drop_index('idx_spu_id', table_name='biz_spu_image')
    op.drop_table('biz_spu_image')
    op.drop_index('idx_category_status', table_name='biz_spu')
    op.drop_index('idx_brand_id', table_name='biz_spu')
    op.drop_table('biz_spu')
    op.drop_table('biz_sku_stock')
    op.drop_index('idx_spu_id', table_name='biz_sku')
    op.drop_table('biz_sku')
    op.drop_index('idx_user_id', table_name='biz_refund')
    op.drop_index('idx_status', table_name='biz_refund')
    op.drop_index('idx_order_no', table_name='biz_refund')
    op.drop_index('idx_order_item_id', table_name='biz_refund')
    op.drop_table('biz_refund')
    op.drop_index('idx_spu_time', table_name='biz_product_review')
    op.drop_index('idx_spu_id_score', table_name='biz_product_review')
    op.drop_table('biz_product_review')
    op.drop_index('idx_status_update', table_name='biz_payment')
    op.drop_index('idx_order_no', table_name='biz_payment')
    op.drop_table('biz_payment')
    op.drop_index('idx_order_id', table_name='biz_order_log')
    op.drop_table('biz_order_log')
    op.drop_index('idx_user_id', table_name='biz_order_item')
    op.drop_index('idx_spu_id', table_name='biz_order_item')
    op.drop_index('idx_order_no', table_name='biz_order_item')
    op.drop_index('idx_order_id', table_name='biz_order_item')
    op.drop_table('biz_order_item')
    op.drop_index('idx_user_status', table_name='biz_order')
    op.drop_index('idx_status_create', table_name='biz_order')
    op.drop_index('idx_create_time', table_name='biz_order')
    op.drop_table('biz_order')
    op.drop_index('idx_user_read_time', table_name='biz_message')
    op.drop_table('biz_message')
    op.drop_table('biz_freight_template')
    op.drop_index('idx_delivery_id', table_name='biz_delivery_trace')
    op.drop_table('biz_delivery_trace')
    op.drop_index('idx_order_no', table_name='biz_delivery')
    op.drop_table('biz_delivery')
    op.drop_index('idx_status_time', table_name='biz_coupon_template')
    op.drop_table('biz_coupon_template')
    op.drop_index('idx_parent_id', table_name='biz_category')
    op.drop_table('biz_category')
    op.drop_table('biz_cart')
    op.drop_table('biz_brand')
    op.drop_index('idx_user_id', table_name='biz_address')
    op.drop_table('biz_address')
    op.drop_index('idx_conversation_id', table_name='ai_message')
    op.drop_table('ai_message')
    op.drop_index('idx_domain_enabled', table_name='ai_kb_document')
    op.drop_table('ai_kb_document')
    op.drop_index('idx_domain_status', table_name='ai_kb_chunk')
    op.drop_index('idx_document_id', table_name='ai_kb_chunk')
    op.drop_table('ai_kb_chunk')
    op.drop_index('idx_queue_status_time', table_name='ai_handoff_record')
    op.drop_index('idx_conversation_id', table_name='ai_handoff_record')
    op.drop_index('idx_agent_status', table_name='ai_handoff_record')
    op.drop_table('ai_handoff_record')
    op.drop_index('idx_conversation_id', table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index('idx_user_id', table_name='ai_conversation')
    op.drop_index('idx_status_update', table_name='ai_conversation')
    op.drop_table('ai_conversation')
    op.drop_table('ai_agent')
    # ### end Alembic commands ###
